### Plugin Integration

# Add Magic NPC trait (/trait magic) to Citizens
enable_citizens: true

# Allow wands to be purchased on Essentials' signs, if present.
enable_essentials_signs: true

# Allow integration with LibsDisguises, spells can be restricted if disguised
enable_libsdisguises: true

# Update dynmap when constructing, if dynmap is present.
dynmap_update: true

# Show wands as dynmap markers, if dynmap is present
dynmap_show_wands: true

# Show spell casts as dynmap polylines, if dynmap is present
dynmap_show_spells: true

# Only show spell casts from players
dynmap_only_player_spells: false

# Enable worldguard protection against construction spells, and PVP
region_manager_enabled: true

# Enable Factions protection against construction spells
factions_enabled: true

# Enable PvPManager integration for PVP spells
pvp_manager_enabled: true

# Enable Towny integration for Build checks
towny_enabled: true

# All spells are allowed in the wilderness
towny_wilderness_bypass: true

# Enable GriefPrevention integration for Build checks
grief_prevention_enabled: true

# Enable PreciousStones integration for Build and PVP checks
precious_stones_enabled: true
# Players who can build in a field can cast ANY spell in that field,
# regardless of other region perms
precious_stones_override: true

# Enable NCP integration- set to false to disable Magic adding
# exemptions to players when casting spells. (e.g. survival_fly on brooms)
ncp_enabled: true

# Enable Lockette integration for Build checks
lockette_enabled: true

# Enable MVCore integration for PVP checks
multiverse_enabled: true

# Disable all build-related checks
bypass_build: false

# Disable all block-breaking checks
bypass_break: false

# Disable all pvp-related checks
bypass_pvp: false

# Set to "true" to ignore pvp_restricted on any spells
allow_pvp_restricted: false

# Will consider all spells as pvp spells
pvp_restricted: false

# Use scoreboard teams for friendly fire
# This will prevent players on the same scoreboard team from
# targeting each other with spells.
use_scoreboard_teams: false

# If not using scoreboard teams or Heroes parties, should players be "friends" by default?
# This will affect being able to cast healing or other perk type spells on other players.
# This does not affect targeting with normal (damaging, etc) spells.
default_friendly: true

# Which mobs types should be considered friendly by default.
# these mobs can still be targeted by damaging spells, but they can also be targeted by friendly healing or perk spells.
friendly_entity_types:
- chicken
- cow
- donkey
- villager
- horse
- iron_golem
- llama
- mule
- ocelot
- parrot
- pig
- polar_bear
- rabbit
- sheep
- snowman
- wolf

### Heroes/Skills configuration

# Show Heroes skills in the /mskills menu, if Heroes is present
skills_use_heroes: true

# Use Heroes mana, if Heroes is present
use_heroes_mana: true

# Spells that don't bypass friendly fire will check Heroes' parties
use_heroes_parties: true

# Use this to prefix skills added via the Magic skill pack
# This can be used to avoid conflicts with public or other skills
heroes_skill_prefix: ""

# Show all Magic spells the player has permission to cast in the /mskills menu
# This might make opening the skills menu lag if you have a lot of spells.
skills_use_permissions: false

### SkillAPI configuration
skillapi_enabled: true

# Use Skill API mana, if Skill API is present
use_skillapi_mana: false

# Allow magic placeholders in PlacerHolder API
placeholder_api_enabled: true

# Enable the Light action using Light API
light_api_enabled: true

# MobArena integration
mobarena:
  # Use this to disable all MobArena integration
  enabled: true
  # Set this to true for magic build/break permissions to respect protected arenas
  protect: false
  # This can be used to protect specific arenas by name
  # protected:
  # - arena1
  # - arena2

# Skript integration will add cast events and effect
skript_enabled: true

# Citadel integration
citadel:
  # Disable integration
  enabled: true

  # Non-player reinforcements will be indestructible to spells
  reinforcements_indestructible: false

  # Player reinforcements will be indestructible to spells
  player_reinforcements_indestructible: false

  # Reinforcements will be taken into account in the BreakBlock action
  # Spells that use ModifyBlock to directly erase blocks will still be able to destroy
  # reinforced blocks, unless the above flags are set.
  reinforcement_durability: true

# The folder and file path to use for loading schematics. This will be relative to
# The server's /plugins folder.
# You can use WorldEdit's schematics folder for easy access to saved schematics.
# You can use this folder to override the built-in schematics, such as replacing the schematics
# used for Tent or Cage.
schematic_files: WorldEdit/schematics/