# This resource pack will automatically be used if none is defined in your server.properties
# Set this to "" if you have some other plugin or Bungee managing resource packs.
resource_pack: "https://s3-us-west-2.amazonaws.com/elmakers/Magic/Magic-RP-8.zip"

# Use this to turn off all resource pack functionality
enable_resource_pack: true

# This will delay sending resource packs to players. This can mitigate issues with the vanilla
# client timing out on connect due to RP processing on potato computers.
# This value is in milliseconds.
# Set this to 0 to set resource packs immediately on join.
resource_pack_delay: 2000

# Set this to true to turn on the player skull-based spell icons
# This may be needed if you have disabled the RP, spell icons are in the RP.
url_icons_enabled: false

# Set this to allow Magic to periodically check for updates to the resource pack.
# Setting this to false is the same as setting resource_pack_check_interval to 0.
enable_resource_pack_check: true

# Set this to zero to turn off periodic RP update checks. The default is every five minutes.
# This is done in a separate thread to avoid interfering with the main server thread.
# Note that this value is in minutes!
resource_pack_check_interval: 5

# Set this to true, and resource packs will not be sent to payers on join, instead they will be prompted
resource_pack_prompt: false